const SUPPORTED_COUNTRIES = [
  'US', 'CA', 'UK', 'GB', 'DE', 'FR', 'IT', 'ES', 'NL', 'BE', 'CH', 'AT',
  'SE', 'NO', 'DK', 'FI', 'PL', 'CZ', 'HU', 'RO', 'BG', 'HR', 'SI', 'SK',
  'LT', 'LV', 'EE', 'IE', 'PT', 'GR', 'CY', 'MT', 'LU', 'IS', 'LI', 'MC',
  'SM', 'AD', 'VA', 'BR', 'MX', 'AR', 'CL', 'CO', 'PE', 'VE', 'EC', 'UY',
  'PY', 'BO', 'GY', 'SR', 'FK', 'GF', 'JP', 'CN', 'IN', 'KR', 'TW', 'HK',
  'SG', 'MY', 'TH', 'VN', 'PH', 'ID', 'MM', 'KH', 'LA', 'BN', 'MO', 'AU',
  'NZ', 'FJ', 'PG', 'NC', 'VU', 'SB', 'TO', 'WS', 'KI', 'TV', 'NR', 'PW',
  'MH', 'FM', 'ZA', 'NG', 'EG', 'KE', 'GH', 'UG', 'TZ', 'ZM', 'ZW', 'MW',
  'MZ', 'MG', 'MU', 'SC', 'RE', 'YT', 'KM', 'DJ', 'SO', 'ET', 'ER', 'SD',
  'SS', 'TD', 'CF', 'CM', 'GQ', 'GA', 'CG', 'CD', 'AO', 'ST', 'BF', 'ML',
  'NE', 'CI', 'GN', 'SN', 'GM', 'GW', 'CV', 'SL', 'LR', 'MA', 'DZ', 'TN',
  'LY', 'EH', 'MR', 'IL', 'PS', 'JO', 'LB', 'SY', 'IQ', 'SA', 'YE', 'OM',
  'AE', 'QA', 'BH', 'KW', 'IR', 'AF', 'PK', 'BD', 'LK', 'MV', 'BT', 'NP',
  'MN', 'KZ', 'KG', 'TJ', 'TM', 'UZ', 'RU', 'BY', 'UA', 'MD', 'GE', 'AM',
  'AZ', 'TR', 'CY', 'AL', 'ME', 'RS', 'BA', 'MK', 'XK'
];

const COUNTRY_MAPPINGS = {
  'US': { location: 'United States', currency: 'USD', language: 'en' },
  'CA': { location: 'Canada', currency: 'CAD', language: 'en' },
  'UK': { location: 'United Kingdom', currency: 'GBP', language: 'en' },
  'GB': { location: 'United Kingdom', currency: 'GBP', language: 'en' },
  'DE': { location: 'Germany', currency: 'EUR', language: 'de' },
  'FR': { location: 'France', currency: 'EUR', language: 'fr' },
  'IT': { location: 'Italy', currency: 'EUR', language: 'it' },
  'ES': { location: 'Spain', currency: 'EUR', language: 'es' },
  'NL': { location: 'Netherlands', currency: 'EUR', language: 'nl' },
  'BE': { location: 'Belgium', currency: 'EUR', language: 'nl' },
  'CH': { location: 'Switzerland', currency: 'CHF', language: 'de' },
  'AT': { location: 'Austria', currency: 'EUR', language: 'de' },
  'SE': { location: 'Sweden', currency: 'SEK', language: 'sv' },
  'NO': { location: 'Norway', currency: 'NOK', language: 'no' },
  'DK': { location: 'Denmark', currency: 'DKK', language: 'da' },
  'FI': { location: 'Finland', currency: 'EUR', language: 'fi' },
  'PL': { location: 'Poland', currency: 'PLN', language: 'pl' },
  'CZ': { location: 'Czech Republic', currency: 'CZK', language: 'cs' },
  'HU': { location: 'Hungary', currency: 'HUF', language: 'hu' },
  'RO': { location: 'Romania', currency: 'RON', language: 'ro' },
  'BG': { location: 'Bulgaria', currency: 'BGN', language: 'bg' },
  'HR': { location: 'Croatia', currency: 'EUR', language: 'hr' },
  'SI': { location: 'Slovenia', currency: 'EUR', language: 'sl' },
  'SK': { location: 'Slovakia', currency: 'EUR', language: 'sk' },
  'LT': { location: 'Lithuania', currency: 'EUR', language: 'lt' },
  'LV': { location: 'Latvia', currency: 'EUR', language: 'lv' },
  'EE': { location: 'Estonia', currency: 'EUR', language: 'et' },
  'IE': { location: 'Ireland', currency: 'EUR', language: 'en' },
  'PT': { location: 'Portugal', currency: 'EUR', language: 'pt' },
  'GR': { location: 'Greece', currency: 'EUR', language: 'el' },
  'JP': { location: 'Japan', currency: 'JPY', language: 'ja' },
  'CN': { location: 'China', currency: 'CNY', language: 'zh' },
  'IN': { location: 'India', currency: 'INR', language: 'en' },
  'KR': { location: 'South Korea', currency: 'KRW', language: 'ko' },
  'TW': { location: 'Taiwan', currency: 'TWD', language: 'zh' },
  'HK': { location: 'Hong Kong', currency: 'HKD', language: 'en' },
  'SG': { location: 'Singapore', currency: 'SGD', language: 'en' },
  'MY': { location: 'Malaysia', currency: 'MYR', language: 'en' },
  'TH': { location: 'Thailand', currency: 'THB', language: 'th' },
  'VN': { location: 'Vietnam', currency: 'VND', language: 'vi' },
  'PH': { location: 'Philippines', currency: 'PHP', language: 'en' },
  'ID': { location: 'Indonesia', currency: 'IDR', language: 'id' },
  'AU': { location: 'Australia', currency: 'AUD', language: 'en' },
  'NZ': { location: 'New Zealand', currency: 'NZD', language: 'en' },
  'BR': { location: 'Brazil', currency: 'BRL', language: 'pt' },
  'MX': { location: 'Mexico', currency: 'MXN', language: 'es' },
  'AR': { location: 'Argentina', currency: 'ARS', language: 'es' },
  'CL': { location: 'Chile', currency: 'CLP', language: 'es' },
  'CO': { location: 'Colombia', currency: 'COP', language: 'es' },
  'PE': { location: 'Peru', currency: 'PEN', language: 'es' },
  'VE': { location: 'Venezuela', currency: 'VES', language: 'es' },
  'EC': { location: 'Ecuador', currency: 'USD', language: 'es' },
  'UY': { location: 'Uruguay', currency: 'UYU', language: 'es' },
  'PY': { location: 'Paraguay', currency: 'PYG', language: 'es' },
  'BO': { location: 'Bolivia', currency: 'BOB', language: 'es' },
  'ZA': { location: 'South Africa', currency: 'ZAR', language: 'en' },
  'NG': { location: 'Nigeria', currency: 'NGN', language: 'en' },
  'EG': { location: 'Egypt', currency: 'EGP', language: 'ar' },
  'KE': { location: 'Kenya', currency: 'KES', language: 'en' },
  'GH': { location: 'Ghana', currency: 'GHS', language: 'en' },
  'UG': { location: 'Uganda', currency: 'UGX', language: 'en' },
  'TZ': { location: 'Tanzania', currency: 'TZS', language: 'en' },
  'ZM': { location: 'Zambia', currency: 'ZMW', language: 'en' },
  'ZW': { location: 'Zimbabwe', currency: 'ZWL', language: 'en' },
  'MW': { location: 'Malawi', currency: 'MWK', language: 'en' },
  'MZ': { location: 'Mozambique', currency: 'MZN', language: 'pt' },
  'MG': { location: 'Madagascar', currency: 'MGA', language: 'fr' },
  'MU': { location: 'Mauritius', currency: 'MUR', language: 'en' },
  'SC': { location: 'Seychelles', currency: 'SCR', language: 'en' },
  'RU': { location: 'Russia', currency: 'RUB', language: 'ru' },
  'BY': { location: 'Belarus', currency: 'BYN', language: 'be' },
  'UA': { location: 'Ukraine', currency: 'UAH', language: 'uk' },
  'MD': { location: 'Moldova', currency: 'MDL', language: 'ro' },
  'GE': { location: 'Georgia', currency: 'GEL', language: 'ka' },
  'AM': { location: 'Armenia', currency: 'AMD', language: 'hy' },
  'AZ': { location: 'Azerbaijan', currency: 'AZN', language: 'az' },
  'TR': { location: 'Turkey', currency: 'TRY', language: 'tr' },
  'IL': { location: 'Israel', currency: 'ILS', language: 'he' },
  'JO': { location: 'Jordan', currency: 'JOD', language: 'ar' },
  'LB': { location: 'Lebanon', currency: 'LBP', language: 'ar' },
  'SA': { location: 'Saudi Arabia', currency: 'SAR', language: 'ar' },
  'AE': { location: 'United Arab Emirates', currency: 'AED', language: 'ar' },
  'QA': { location: 'Qatar', currency: 'QAR', language: 'ar' },
  'BH': { location: 'Bahrain', currency: 'BHD', language: 'ar' },
  'KW': { location: 'Kuwait', currency: 'KWD', language: 'ar' },
  'OM': { location: 'Oman', currency: 'OMR', language: 'ar' },
  'PK': { location: 'Pakistan', currency: 'PKR', language: 'ur' },
  'BD': { location: 'Bangladesh', currency: 'BDT', language: 'bn' },
  'LK': { location: 'Sri Lanka', currency: 'LKR', language: 'si' },
  'NP': { location: 'Nepal', currency: 'NPR', language: 'ne' },
  'BT': { location: 'Bhutan', currency: 'BTN', language: 'dz' },
  'MV': { location: 'Maldives', currency: 'MVR', language: 'dv' },
  'AF': { location: 'Afghanistan', currency: 'AFN', language: 'fa' },
  'IR': { location: 'Iran', currency: 'IRR', language: 'fa' },
  'IQ': { location: 'Iraq', currency: 'IQD', language: 'ar' },
  'SY': { location: 'Syria', currency: 'SYP', language: 'ar' },
  'YE': { location: 'Yemen', currency: 'YER', language: 'ar' }
};

const CURRENCY_SYMBOLS = {
  'USD': '$',
  'EUR': '€',
  'GBP': '£',
  'JPY': '¥',
  'CNY': '¥',
  'INR': '₹',
  'KRW': '₩',
  'CAD': 'C$',
  'AUD': 'A$',
  'CHF': 'Fr',
  'SEK': 'kr',
  'NOK': 'kr',
  'DKK': 'kr',
  'PLN': 'zł',
  'CZK': 'Kč',
  'HUF': 'Ft',
  'RUB': '₽',
  'BRL': 'R$',
  'MXN': '$',
  'ZAR': 'R',
  'SGD': 'S$',
  'HKD': 'HK$',
  'NZD': 'NZ$',
  'TWD': 'NT$',
  'THB': '฿',
  'MYR': 'RM',
  'IDR': 'Rp',
  'PHP': '₱',
  'VND': '₫',
  'TRY': '₺',
  'ILS': '₪',
  'SAR': '﷼',
  'AED': 'د.إ',
  'PKR': '₨',
  'BDT': '৳',
  'LKR': '₨',
  'NPR': '₨'
};

const ERROR_MESSAGES = {
  INVALID_COUNTRY: 'Invalid or unsupported country code',
  INVALID_QUERY: 'Invalid search query',
  SEARCH_FAILED: 'Search request failed',
  AI_PROCESSING_FAILED: 'AI processing failed',
  NO_RESULTS: 'No results found',
  RATE_LIMIT_EXCEEDED: 'Rate limit exceeded',
  INTERNAL_ERROR: 'Internal server error'
};

const API_LIMITS = {
  SERPAPI_MONTHLY: 100,
  GEMINI_DAILY: 1500,
  GEMINI_MINUTE: 15,
  MAX_RESULTS: 20,
  QUERY_MIN_LENGTH: 2,
  QUERY_MAX_LENGTH: 200
};

module.exports = {
  SUPPORTED_COUNTRIES,
  COUNTRY_MAPPINGS,
  CURRENCY_SYMBOLS,
  ERROR_MESSAGES,
  API_LIMITS
};